---
driver:
  name: docker

driver_config:
  use_sudo: false
  privileged: true
  require_chef_omnibus: false

platforms:
  - name: centos-7
  - name: ubuntu-16.04
  - name: debian-9

provisioner:
  name: salt_solo
  require_chef: false
  salt_version: latest
  formula: clamav
  salt_copy_filter:
    - .kitchen
    - .git
  pillars-from-files:
    clamav.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - clamav
  state_top:
    base:
      '*':
        - clamav

verifier:
  name: serverspec
  use_sudo: yes
  sudo_path: true

suites:
  - name: default
    verifier:
      default_pattern: true
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'
      env_vars:
        SUDO: true
